## No.5(i)

In [1]:
import numpy as np

In [9]:
T=np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(T)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [14]:
InverseT=np.linalg.inv(T)
print(InverseT)

[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


## No.5(ii)

In [15]:
detT=np.linalg.det(T)
print(detT)

0.2299999999999999


### No.5(iv)

In [26]:
TransformT=np.transpose(T)
print(TransformT)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


### No.5(iii) 

In [29]:
DecomposeT=np.delete(T,2,axis=0)
print(DecomposeT)

[[1.  0.2 0.5]
 [0.2 1.  0.8]]
